### PR TITLE
Prepare release v1.8.0

### PR DESCRIPTION
**Pull request by markets**
**DIFF** https://github.com/ondrejbartas/sidekiq-cron/compare/v1.7.0...master

(I'll squash at the end)

### CODE REVIEW

**Comment by markets** [comment]
@honzasterba @ondrejbartas @engwan @cgunther @danilogco are you agree to ship this as `v1.8`?

**Review by honzasterba — APPROVED** [review]

**Review by danilogco — APPROVED** [review]

**Comment by markets** [comment]
ℹ️ We should fix this one before releasing new version: #365

@engwan do you mind to take a look? Sidekiq is introducing a lot of API changes lately... it's becoming hard to keep compatibility for all versions 😅

**Comment by engwan** [comment]
> ℹ️ We should fix this one before releasing a new version: #365
> 
> @engwan do you mind to take a look?
> 
> Sidekiq is introducing a lot of API changes lately... it's becoming hard to keep compatibility for all versions 😅

Good catch. That one was actually caused by me with this bug fix in Sidekiq: https://github.com/mperham/sidekiq/pull/5513

**Comment by markets** [comment]
ℹ️ a couple of commits have been merged to `master`:
- https://github.com/ondrejbartas/sidekiq-cron/commit/b6c856b934af8845d950d094fc9c68ffd3396cf2
- https://github.com/ondrejbartas/sidekiq-cron/commit/704d4367dd8a73055531a5fd55fb61f9c7c1b94d

**Review by honzasterba — APPROVED** [review]
lgtm

**Review by danilogco — APPROVED** [review]

**Comment by serprex** [comment]
Could 1.8.0 include #369 for Sidekiq 7 compatibility?

**Comment by markets** [comment]
@serprex I'll prefer to leave that PR for next iterations, since these changes already solve some problems and Sidekiq is still in beta. Also, it seems after my comment https://github.com/ondrejbartas/sidekiq-cron/pull/369#issuecomment-1265209749 some new code has been pushed... so IMHO better to launch v1.8.0 like it is now, and leave Sidekiq 7 compatibility for future iterations.

**Comment by honzasterba** [comment]
agree with @markets

**Comment by markets** [comment]
`v1.8.0` is out 🚀 https://rubygems.org/gems/sidekiq-cron/versions/1.8.0

Thank you all!

**Pull request merged**
