### PR TITLE
Update README to mention second-precision jobs

### PR DESCRIPTION
**Pull request by tekin**
Updates the README to mention this undocumented (and regularly requested!) feature.

### CODE REVIEW

**Comment by tekin** [comment]
@ondrejbartas coverage has dropped slightly, but the PR is only updating the README. Thoughts?

**Comment by gogiel** [comment]
Thank you for this. Anything blocking the merge?

**Comment by tekin** [comment]
@gogiel not from my perspective.

**Comment by beatak** [comment]
This should be closed and deleted because `.poll_interval` was long gone by v3.4.0

https://github.com/mperham/sidekiq/blob/main/Changes.md#340

which was from 2015.

https://github.com/mperham/sidekiq/commit/149949373fe371a3c2c60a7f7c5984317762d811

**Comment by tekin** [comment]
@beatak thanks for pointing that out. Rather than delete this pull request I've updated it to mention the new configuration mechanism. I've left the PR open as the main point of the PR (to explain how to schedule second-precision jobs) still stands.

**Comment by borisromanov** [comment]
Hi, just stumbling across this now. Any issues with merging this PR so the sidekiq-cron community can benefit?

**Comment by honzasterba** [comment]
needs to be rebased and can be merged

**Comment by markets** [comment]
We also mention the `average_scheduled_poll_interval` options here https://github.com/ondrejbartas/sidekiq-cron#under-the-hood, but with different syntax and different defaults 🤔 should we "unify" or DRY these explanations?

**Review by markets — APPROVED** [review]

**Pull request merged**
