### PR TITLE
Fix rufus-scheduler 3.3.0 ZoTime operation bug.

### PR DESCRIPTION
**Pull request by Junyulive**
ERROR: CRON JOB: can't convert Rufus::Scheduler::ZoTime into an exact number.

### CODE REVIEW

**Comment by tisba** [comment]
Thanks for the quick fix! We were running into this issue as well.

Maybe only slightly related: We are using Rollbar to collect and aggregate exceptions (for web requests and sidekiq jobs etc). However the sidekiq-cron errors, like this one, was only logged. Is there a way to hook into the error handling?

**Comment by ondrejbartas** [comment]
@tisba sidekiq-cron is using original logger from Sidekiq.logger so if you are not getting any logs it means that you are not getting logs from Sidekiq as well

**Comment by tisba** [comment]
@ondrejbartas hmm okay, I'll take another look. maybe I'm mixing things up then. thanks!

**Comment by ondrejbartas** [comment]
@tisba hope you will find a way, or if you find that sidekiq-cron is doing something wierd pls let us know.

**Comment by tisba** [comment]
Sure, will do!

**Comment by tisba** [comment]
Sorry for the noise, I think there might be indeed room for improvement :) I've created a new issue, because I think this is a bit out of scope for this issue here, see https://github.com/ondrejbartas/sidekiq-cron/issues/123.

**Pull request merged**
