### PR TITLE
Support Dark Mode

### LINKED ISSUE #260: Support Dark Mode (Sidekiq v6.0.1)
The latest release of Sidekiq now detects if the user's browser is reporting that it is in 'dark mode' and changes the theme accordingly. However, `sidekiq-cron`'s buttons don't play nicely with this:

Screenshot 2019-10-09 at 23 14 24

### PR DESCRIPTION
**Pull request by Atrox**
Changes the button classes to the ones used in sidekiq.
fixes #260 

image

### CODE REVIEW

**Review by CHTJonas — APPROVED** [review]
Tested as working for me! @ondrejbartas, it would be great to get this merged soon.

**Comment by CHTJonas** [comment]
Poke @ondrejbartas / @Atrox

**Comment by markets** [comment]
Hello @Atrox could you please rebase from master 🙏🏼? 

ℹ️ The Slim templates has been removed

**Comment by markets** [comment]
Thanks for the update @Atrox 🙌🏼 seems fine to me! ✅ 

@CHTJonas do you mind to make quick test again? we'd like to include this in the next release.

**Review by honzasterba — APPROVED** [review]

**Review by mathieujobin — APPROVED** [review]
LGTM

**Pull request merged**
