### PR TITLE
Fixes an issue that prevented the gem to work in previous versions

### LINKED ISSUE #334: sidekiq-cron v1.5.0 was broken older sidekiq versions than 6.4.2
Perhaps these codes in this area is affected?
https://github.com/ondrejbartas/sidekiq-cron/compare/v1.4.0...v1.5.0#diff-06d0d2166cea05c93b3e1f7a9a036e9b0f9472d8f8cd7e63954b3e4b413b9752R10-R23

#### related files
```ruby
# app/workers/hard_worker.rb
class HardWorker
  include Sidekiq::Worker

  def perform(name, count)
    # do something
  end
end

# config/sidekiq.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 5
:queues:
  - default
```

#### console
```ruby
> bundle exec sidekiq
2022-06-09T06:12:23.287Z pid=8830 tid=8xu INFO: Booting Sidekiq 6.4.2 with redis options {:url=>"redis://localhost:6379/1"}
2022-06-09T06:12:23.300Z pid=8830 tid=8xu INFO: Cron Jobs - added job with name: schedule_hard_worker
...
2022-06-09T06:12:23.384Z pid=8830 tid=8xu INFO: Booted Rails 7.0.3 application in development environment
2022-06-09T06:12:23.384Z pid=8830 tid=8xu INFO: Running in ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]
2022-06-09T06:12:23.384Z pid=8830 tid=8xu INFO: See LICENSE and the LGPL-3.0 for licensing details.
2022-06-09T06:12:23.384Z pid=8830 tid=8xu INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2022-06-09T06:12:23.385Z pid=8830 tid=8xu INFO: Starting processing, hit Ctrl-C to stop
2022-06-09T06:12:23.386Z pid=8830 tid=8xu WARN: NoMethodError: undefined method `[]' for Sidekiq:Module

          config[:poll_interval_average] = config[:average_scheduled_poll_interval] || POLL_INTERVAL
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-06-09T06:12:23.386Z pid=8830 tid=8xu WARN: /Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.5.0/lib/sidekiq/cron/poller.rb:13:in `block in initialize'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:73:in `configure_server'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.5.0/lib/sidekiq/cron/poller.rb:12:in `initialize'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.5.0/lib/sidekiq/cron/launcher.rb:17:in `new'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.5.0/lib/sidekiq/cron/launcher.rb:17:in `initialize'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:113:in `new'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:113:in `launch'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:105:in `run'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-6.4.2/bin/sidekiq:31:in `<top (required)>'
/Users/xxx/.rbenv/versions/3.1.2/bin/sidekiq:25:in `load'
/Users/xxx/.rbenv/versions/3.1.2/bin/sidekiq:25:in `<top (required)>'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:48:in `block in <top (required)>'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/xxx/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/libexec/bundle:36:in `<top (required)>'
/Users/xxx/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/Users/xxx/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

## System configuration
* ruby v3.1.2
* rails v7.0.3
* sidekiq v6.4.2 (Older than v6.4.2)
* sidekiq-cron v1.5.0

### PR DESCRIPTION
**Pull request by sandip-mane**
fixes #334

### CODE REVIEW

**Comment by sandip-mane** [comment]
@ondrejbartas please review. It could unblock many of us.

**Comment by sandip-mane** [comment]
Yeah, that way, we could also get rid of the following if statement.

https://github.com/ondrejbartas/sidekiq-cron/blob/c14479a2da7e975ccb389e4725c86038e7e91adc/lib/sidekiq/cron/poller.rb#L20-L25

**Comment by danilogco** [comment]
@ondrejbartas @markets what do you guys think about these organization by supported versions?

**Review by markets — APPROVED** [review]

**Comment by markets** [comment]
Version 1.5.1 pushed to RubyGems 🚀 https://rubygems.org/gems/sidekiq-cron/versions/1.5.1

**Pull request merged**
