### PR TITLE
Fix missing queue name enque! job in web portal.

### PR DESCRIPTION
**Pull request by Junyulive**
@queue_name_with_prefix hasn't initialized properly.

```
[2] pry(#<Sidekiq::Cron::Job>)> self
=> #<Sidekiq::Cron::Job:0x007f9bd948f1a8
 @active_job=false,
 @active_job_queue_name_delimiter="",
 @active_job_queue_name_prefix="",
 @args=[{"type"=>"comments"}],
 @cron="* * * * *",
 @description="",
 @errors=[],
 @fetch_missing_args=false,
 @klass="Worker::FetchLoader",
 @last_enqueue_time=2016-09-22 19:14:21 +0800,
 @message="{\"retry\":true,\"queue\":\"comments\",\"class\":\"Worker::FetchLoader\",\"args\":[{\"type\":\"comments\"}]}",
 @name="comments_loader",
 @queue="comments",
 @status="enabled">

[3] pry(#<Sidekiq::Cron::Job>)> self.queue_name_with_prefix
=> "comments"
[4] pry(#<Sidekiq::Cron::Job>)> @queue_name_with_prefix
=> nil
```

### CODE REVIEW

**Comment by ondrejbartas** [comment]
@Junyulive what version of sidekiq cron do you use?

**Comment by Junyulive** [comment]
@ondrejbartas I just got the updates from the newest version (you did fixed the missing queue name bug). But I fixed an additional issue with the active job queue name (	_Active job const set queue name without prefix_).

**Comment by lolychee** [comment]
+1

**Comment by ondrejbartas** [comment]
sorry for delay.. Thank you for your PR

**Pull request merged**
